<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <artifactId>io-takamaka-code-examples</artifactId>
  <packaging>pom</packaging>
  <name>io-takamaka-code-examples</name>
  <version>${io.takamaka.code.version}</version>
  <description>This module contains the examples of smart contracts from the Hotmoka tutorial.</description>

  <parent>
    <groupId>io.hotmoka</groupId>
    <artifactId>io-takamaka-code-parent</artifactId>
    <version>parent</version>
  </parent>

  <profiles>
	<profile>
	  <id>release</id>
      <build>
	    <plugins>
          <plugin>
            <groupId>org.sonatype.plugins</groupId>
            <artifactId>nexus-staging-maven-plugin</artifactId>
            <version>1.6.13</version>
            <configuration>
              <skipNexusStagingDeployMojo>false</skipNexusStagingDeployMojo>
            </configuration>
          </plugin>
	    </plugins>
      </build>
	</profile>
  </profiles>

  <modules>
  	<module>io-takamaka-code-examples-auction</module>
  	<module>io-takamaka-code-examples-auction_events</module>
  	<module>io-takamaka-code-examples-ponzi_simple</module>
  	<module>io-takamaka-code-examples-ponzi_payable</module>
  	<module>io-takamaka-code-examples-ponzi_annotations</module>
  	<module>io-takamaka-code-examples-ponzi_view</module>
  	<module>io-takamaka-code-examples-ponzi_gradual</module>
  	<module>io-takamaka-code-examples-tictactoe</module>
  	<module>io-takamaka-code-examples-tictactoe_improved</module>
  	<module>io-takamaka-code-examples-erc20</module>
  	<module>io-takamaka-code-examples-erc721</module>
  	<module>io-takamaka-code-examples-family</module>
  	<module>io-takamaka-code-examples-family_storage</module>
  	<module>io-takamaka-code-examples-family_exported</module>
  	<module>io-takamaka-code-examples-family_errors</module>
  </modules>
</project>